# Project Information
site_name: SJSU-DEV2
# Configuration
theme:
  name: 'material'
  # custom_dir: css/
  # include_sidebar: true
  highlightjs: true
  hljs_style:
    - monokai
  extra_css:
    - 'stylesheets/extra.css'

docs_dir: documentation/

markdown_extensions:
  - admonition
  - pymdownx.mark # highlighting
  - pymdownx.superfences # nest code
  - codehilite # code syntax coding
  - toc:
      permalink:

# Navigation
nav:
  - Home: 'index.md'
  - Introduction:
    - 'introduction/getting_started_sjtwo.md'
    - 'introduction/connecting_debugger.md'
    - 'introduction/flashing.md'
    - 'introduction/device_debugging.md'
    - 'introduction/project.md'
    - 'introduction/library.md'
    - 'introduction/reference.md'
  - Software Architecture:
    - 'software_architecture/error_handling.md'
    - 'software_architecture/multi_platform.md'
    - 'software_architecture/clock_systems.md'
    - 'software_architecture/fatfs.md'
    - 'software_architecture/unit_testing.md'
  - Libraries:
    - 'libraries/bit.md'
    - 'libraries/math_utilities.md'
    - 'libraries/map.md'
  - How To Contribute:
    - 'contributing/philosophy.md'
    - 'contributing/levels.md'
    - 'contributing/level_guide/L0_platform.md'
    - 'contributing/level_guide/L1_peripheral.md'
    - 'contributing/level_guide/L2_hal.md'
    - 'contributing/level_guide/L3_application.md'
    - 'contributing/presubmit-checks.md'
    - 'contributing/style.md'
    - 'contributing/techniques/left-to-right.md'
  - Design Documents:
    - L0 Platform:
      - 'design_docs/L0/none.md'
    - L1 Peripheral:
      - 'design_docs/L1/counter.md'
      - 'design_docs/L1/pin.md'
      - 'design_docs/L1/system_controller.md'
      - System Controllers:
        - 'design_docs/L1/msp432p401r/system_controller.md'
    - L2 Hardware Abstraction:
      - Sensors:
        - 'design_docs/L2/accelerometer.md'
        - Accelerometers Drivers:
          - 'design_docs/L2/accelerometer/mma8452q.md'
        - Environment:
          - 'design_docs/L2/light_sensor_interface.md'
          - 'design_docs/L2/temperature_sensor_interface.md'
          - Light Sensor Drivers:
            - 'design_docs/L2/temt6000x01.md'
          - Temperature Sensor Driver:
            - 'design_docs/L2/si7060.md'
            - 'design_docs/L2/tmp102.md'
      - Communication:
        - 'design_docs/L2/infrared_receiver_interface.md'
        - Infrared:
          - 'design_docs/L2/tsop752.md'
    - L3 Application:
      - 'design_docs/L3/periodic_scheduler.md'
      - 'design_docs/L3/task_interface.md'
      - 'design_docs/L3/task_scheduler.md'
    - Utility:
      - 'design_docs/utility/none.md'
    - Testing:
      - 'design_docs/testing/none.md'
    - Third Party Software:
      - 'design_docs/third_party/none.md'
    - Template:
      - 'design_docs/template/template.md'
  - 'about.md'
  - 'copyrights.md'
